[package]
name = "straal"
version = "0.1.0"
authors = ["MT <mtesseracttech@gmail.com>"]
edition = "2018"

[dependencies]
glium = "*"
image = "*"
rand = "*"
criterion = "*"


[[bench]]
name = "matrix_benchmarks"
harness = false